#===- Slimmer/test/TestSegmentTree/Makefile ----------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL := ../..
TOOLNAME = test-segtree
USEDLIBS = SlimmerUtil.a

include $(LEVEL)/Makefile.common


