#===- Slimmer/tools/ReadTrace/Makefile ----------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL := ../..
TOOLNAME = group-memory
USEDLIBS = SlimmerUtil.a

include $(LEVEL)/Makefile.common
LIBS += -lboost_system -lboost_iostreams

