##===- Slimmer/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS = SlimmerUtil SlimmerTrace SlimmerRuntime SlimmerLTO

include $(LEVEL)/Makefile.common
