#===- Slimmer/tools/ExtractMemoryDependency/Makefile ----------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL := ../..
TOOLNAME = extract-memory-dependency
USEDLIBS = SlimmerUtil.a

include $(LEVEL)/Makefile.common
LIBS += -lboost_system -lboost_iostreams -llz4

