##===- Slimmer/tools/Makefile ----------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS = SlimmerGold PinTool ReadTrace ExtractMemoryDependency ExtractImpactfulFunCall ExtractUneededOperation

include $(LEVEL)/Makefile.common
